CovidStateDashboard/datasetUpdates/index.js

The auto PRs created need different names for the non-master ones (staging).

Branch name note for non-master

---

CovidStateDashboard/datasetUpdates/index.js
CovidStateDashboard/gitHub/index.js
CovidStateDashboard/index.js
CovidStateDashboard/slackBot/index.js
CovidWeeklyTierUpdate/doUpdate.js
CovidWeeklyTierUpdate/function.json
CovidWeeklyTierUpdate/index.js
sandbox/index.js

Tuesday Dimmer Switch auto PR

---

CovidStateDashboard/datasetUpdates/index.js
CovidStateDashboard/gitHub/index.js
CovidStateDashboard/index.js
sandbox/index.js

This should make the stats approval automatic.

Updating daily stats job to auto approve

---

CovidStateDashboard/gitHub/index.js
CovidTranslationPrApproval/function.json
CovidTranslationPrApproval/index.js
CovidTranslationPrApproval/worker/index.js
sandbox/index.js

Poll the PR list every 5 minutes and look for open translation labeled PRs that have passed all their checks.  Merge them and delete branches.  Works on the oldest first.  Stops processing if the oldest PR does not pass.  Not pass could mean "in progress" or "completed and failed".

Auto approving translations

---

CovidWeeklyTierUpdate/doUpdate.js
CovidWeeklyTierUpdate/function.json
CovidWeeklyTierUpdate/index.js
common/gitHub/index.js
sandbox/index.js

Run the query every day.  If there is new tier data, create a PR with it.

Check tiers daily, create a PR when there is a change

---

CovidEquityData/index.js
sandbox/index.js

Attempting to improve query access and reusability

covid eq queries

---

CovidTranslationPrApproval/worker/index.js

Fixed bug. Need some JS linting to prevent.

Fixing Translation PR auto approval

---

CovidEquityData/index.js
common/gitHub/index.js
sandbox/index.js

This will add the vargoCDPH review to the new equity pr

Adding reviewer to prs

---

CovidEquityData/gitHub.js
CovidEquityData/index.js

Tried to setup github PR template for this but the PR opened by the API doesn't use it so adding in the body copy to the request

add body to opened PR

---

CovidWeeklyTierUpdate/doUpdate.js
CovidWeeklyTierUpdate/function.json

(Update, will now update existing PRs)
Was running at 11:10am.  Changed to run at 9am.
Should be no need to run the HTTP version.

Running auto tier update earlier.

---

CovidEquityData/index.js

Update the language to the info provided by Corey
Remove Sindhu from approvers list until she accepts the github invite so that step will work

temporarily remove sindhu, add new PR approval language

---

.vscode/launch.json
CovidEquityData/function.json
CovidEquityData/index.js
sandbox/index.js

Minor fixes/comments on CovidEquityData cron.
To manually run a cron, you will need a local.settings.json (contact jbum for a copy).
```
$ cd sandbox
$ node index.js
```
```
1. Run CovidEquityData
2. Run doDailyStatsPr
3. Run doTranslationPrUpdate
4. Run doWeeklyUpdatePrs
q. quit
Your choice>
```

Added menu to sandbox so it can be used to manually run a few different crons. 

---

CovidEquityData/index.js
package-lock.json

This will add a slack note every time equity runs/starts
(also fixing package lock name)

Adding reports for start/finish

---

CovidEquityData/index.js

This makes the code ignore the PR creation on re-runs, and fixes the start/end run messages

messaging fixes and re-run support

---

CovidNewsFeed/index.js
CovidNewsFeed/sources/cdph.js

Fixes a lot of the date parsing issues.
(Also turned off the notifications for all runs)

Fixes for newsfeed

---

CovidEquityData/function.json

Switched EquityData cron to tuesday only.

---

.vscode/launch.json
CovidStateDashboard/datasetUpdates/index.js
package-lock.json
package.json
sandbox/index.js

This replaces the custom github module

Using github-api NPM for Daily Stats

---

.vscode/launch.json
CovidSiteHealth/function.json
CovidSiteHealth/index.js
CovidSiteHealth/worker.js
common/slackBot/index.js
sandbox/index.js

- Checks for site up
- Checks for recent deployment and matches to Slack

Site Health Monitor

---

CovidSiteHealth/worker.js
common/slackBot/index.js

Adding "white check mark" reactions for replies it adds.
removing some redundant awaits on slackbot functions

Adding reactions to chatbot, fixing async awaits

---

common/slackBot/index.js

Multiple errors within the same hour will appear as stacked replies.

Stacking Slack errors in replies

---

.vscode/launch.json
CovidStateDashboardV2/function.json
CovidStateDashboardV2/index.js
CovidStateDashboardV2/worker.js
sandbox/index.js

This robot will automate the creation of the following file...
https://files.covid19.ca.gov/data/daily-stats-v2.json

Ccg 1069 update data query for tracking covid19 box

---

CovidStateDashboardV2/function.json
CovidStateDashboardV2/index.js

Snowflake table changed and broke the query.  Shutting it off until we get answers.
Also moving the time up 15 mins to prevent both jobs from running at the same time.

query got busted.  Turning off.

---

CovidNewsFeed/sources/cdph.js

This finds the new stories, and loops through them, but when I run locally, it still does a write-0. Investigating. Let's merge this and see if it behaves differently on Azure.

Corrected CDPH URL for 2021.

---

CovidNewsFeed/sources/cdph.js

This is a quick fix to the missing news problem. Will need a longer term fix before 2022.

Fixed 2021 parsing issue with CDPH news items.

---

.vscode/launch.json
common/gitHub/index.js

Extracting some of the improvement from the other PR.
https://github.com/cagov/Cron/pull/65

Pre pr debug updates (Approve before #65)

---

.vscode/launch.json
CovidTranslationPrApproval/worker/index.js
sandbox/index.js

Swapping in the new github module for auto-translation approval.
For...
https://digital-ca-gov.atlassian.net/browse/CCG-1064

Translation PR approver using new github module

---

CovidStateDashboardV2/worker.js
common/snowflakeQueryV2/index.js

- Adding support for multiple Snowflake data sources.
- Parallel query support
- Automating vaccine data.

Ccg 1365 update snowflake cron data access to support separ

---

common/slackBot/index.js

Adding comment structures to common methods, starting with Slackbot.
(Draft, needs some more review)

JSDOC compatible method comments

---

CovidStateDashboardV2/worker.js
common/snowflakeQueryV2/index.js

Adding the JSDOC comments to the Snowflake Module V2
- Removed env var dependency
- Using native Snowflake interface for comments

Adding JSDOC comments to Snowflake Module V2

---

CovidEquityData/index.js

Making some code simplifications now that I've had to dive into the EQ data.

Eq process improvement

---

.vscode/launch.json
CovidVaccineEquity/function.json
CovidVaccineEquity/index.js
CovidVaccineEquity/worker.js
common/SQL/CDTCDPH_VACCINE/vaccines_by_age.sql
common/SQL/CDTCDPH_VACCINE/vaccines_by_gender.sql
common/SQL/CDTCDPH_VACCINE/vaccines_by_race_eth.sql
sandbox/index.js

Creates the data for `data/vaccine-equity/` in the static repo.

CovidVaccineEquity

---

CovidTranslationPrApproval/worker/index.js

Found I have to query the PR directly to get mergability.  This should prevent merge errors when there is a conflict.

translation approval checking mergability

---

CovidStateDashboardV2/worker.js

Checks the result objects for nulls.
Will throw an exception if any of the state dashboard data is missing (like if a field name gets changed).

checking dashboard data for nulls

---

CovidVaccineEquity/worker.js
common/SQL/CDTCDPH_VACCINE/vaccines_by_age.sql

Adding unknown age, for 1-1-1900 DOB and other strange things.
Changing gender to single letter on input.

Vaccine equity dataset changes

---

common/SQL/CDTCDPH_VACCINE/vaccines_by_age.sql
common/SQL/CDTCDPH_VACCINE/vaccines_by_gender.sql
common/SQL/CDTCDPH_VACCINE/vaccines_by_race_eth.sql

MIXED_COUNTY was re-added to the main view, so we need to remove the custom column

removing mixed_county because the view has it now

---

CovidStateDashboard/function.json
CovidStateDashboardV2/function.json
CovidVaccineEquity/function.json
CovidVaccineHPI/function.json

New cron schedules for tomorrow.
Spacing them out by a minute to reduce overrun.

Cron timers to get jobs started at 9:20 ish.

---

common/SQL/CDT_COVID/Equity/SocialData.sql

Temp fix to deal with duplicate records in social det.

temp fix for duplicate social det

---

CovidStateDashboardV2/worker.js

Adding type comments to help with modularity later.

V2 branch cleanup

---

CovidStateDashboardV2/daily-stats-v2.js
CovidStateDashboardV2/worker.js
common/SQL/CDT_COVID/Infections-by-group/infections-by-group.sql

Using new SQL for V2 infections by group.
(Also adding published date to meta)

New SQL from Daniel Molitor

---

CovidVaccineEquity/function.json

The vaccine equity charts on the /vaccines page are supposed to update daily

change schedule

---

CovidEquityData/function.json
CovidStateDashboard/function.json
CovidStateDashboardV2/function.json
CovidVaccineEquity/function.json
CovidVaccineHPI/function.json
CovidWeeklyTierUpdate/function.json

Revert this PR after deployment to switch them back on.

Temporarily disabling certain cron jobs

---

CovidTranslationPrApproval/index.js

When we are ready to auto-approve again...

Turning translation PR approval back on

---

CovidVaccineEquity/worker.js
common/SQL/CDTCDPH_VACCINE/vaccines_by_age.sql
common/SQL/CDTCDPH_VACCINE/vaccines_by_gender.sql
common/SQL/CDTCDPH_VACCINE/vaccines_by_race_eth.sql

Using queries provided by Rui Zhao.
Input schema gender changes to single letter (M/F/U)

New Vaccine Equity Queries

---

covidE2E/package-lock.json
covidE2E/package.json

Trying to resolve "Dependabot alerts"

updating CovidE2E packages

---

CovidStateDashboard/index.js
CovidStateDashboardV2/index.js
CovidVaccineHPI/index.js
CovidVaccineHPIV2/index.js
CovidWeeklyTierUpdate/index.js

All messages updated except for CovidEquityData

Updating all cron messaging

---

CovidAutoBuilder/function.json
CovidAutoBuilder/index.js
CovidAutoBuilder/package-lock.json
CovidAutoBuilder/package.json
CovidAutoBuilder/worker.js
sandbox/index.js

This is a new cron (CovidAutoBuilder) that checks when the site needs to be built because the summary-box data has been updated.  Runs every ten minutes. I’m using _puppeteer_ to fetch the current vaccines number from the home page and _fetch_ to retrieve the JSON from files.covid, and comparing the numbers.
Puppeteer is not currently part of packages.json, so I’ve set up an additional packages.json in the CovidAutoBuilder/ directory (similar to what CovidE2E does. Is this kosher?  Will puppeteer work ok on azure? Should I just add it to the root-directory package.json? 
Code can be run locally using node sandbox/index.js 11
Currently it just fetches and compares the two values.  Does a few bits of sanity checking which cause it to throw errors.

Initial implementation of CovidAutoBuilder. In Progress.

---

CovidAutoBuilder/function.json
CovidAutoBuilder/index.js
CovidAutoBuilder/worker.js

Cron still does nothing, but should correctly notify the testingbot channel as to whether we need a build or not.

Fixed bug with boolean. Renabled cron for testing.

---

CovidAutoBuilder/function.json
CovidAutoBuilder/index.js
CovidAutoBuilder/worker.js

Gonna test for the next couple runs, then turn testing off.  This works locally.
Using a 15 minute timer so that if there was a previous auto-build, it should be done by the time we run again.

Added git PR support. 15 minute timer. Testing on (forces builds).

---

CovidTranslationPrApproval/worker/index.js

Allowing zero width space (8203, \u200B) for translations

Support for zero width space

---

CovidAutoBuilder/index.js
CovidAutoBuilder/worker.js

Fixed bug with git PR submission caused by my changing the time formatting, added delay.

Ccg 1859/auto builder

---

CovidStateDashboardV2/function.json
CovidStateDashboardV2/index.js

State Dash Time Change

---

CovidStateDashboardTables/function.json

changed to 9:10 instead of 3:20

Fixing State Dash tables start time

---

CovidTranslationPrApproval/worker/index.js

Auto approval needs to allow for tabs

Allowing tabs in translation

---

CovidTranslationPrApproval/worker/index.js

- fixed issues with whitespace only patches.
- adding whitelist for "word joiner" char.

Blank patch support and word joiner char

---

CovidStateDashboardTables/gitTreeCommon.js
CovidStateDashboardTables/index.js
CovidStateDashboardTables/worker.js

Splitting the data into 3 Prs.
```
{
title : "Covid Dashboard Tables - Tests",
folders : [
"total-tests",
"positivity-rate"
]
},
{
title : "Covid Dashboard Tables - Patients",
folders : [
"patients",
"icu-beds"
]
},
{
title : "Covid Dashboard Tables - Cases/Deaths",
folders : [
"confirmed-cases",
"confirmed-deaths"
]
}
```

Separating data Prs for State Dash D3

---

CovidVaccineHPIV2/function.json

This edit to the schedule is intended to make it run only on Wednesdays which is the desired update schedule for this chart per Hannah

only run this on Wednesdays

---

CovidVaccineEquity/function.json

this will make vaccine equity charts refresh update line up with everything else on that page

run on wednesdays only

---

CovidStateDashboardTables/worker.js

Hoping to get rid of error between approvals

Adding delay between approvals

---

.vscode/launch.json
CovidStateDashboardTables/function.json
CovidStateDashboardTables/gitTreeCommon.js
CovidStateDashboardTables/worker.js
CovidTranslationPrApproval/AutoApprover.js
CovidTranslationPrApproval/AutoApproverLabels.json
CovidTranslationPrApproval/index.js
package-lock.json
package.json
sandbox/index.js

- Adding a PR auto approver for defined labels
- Changing D3 tables run time to 7am (removing auto pr approval)
- D3 tables will create a "Approve at 9am" tag
- Targeting covid-static-data repo
- Adding "moment.js" to deal with time zone issues

Auto approver

---

CovidStateDashboardTables/function.json
CovidWeeklyTierUpdateHttpTrigger/index.js

Carter can you confirm these two spelling fixes are harmless?

Corrected spellings.

---

CovidStateDashboardTables/worker.js

CovidStateDashboardTables will refresh this branch whenever it finishes creating the PRs.
CovidStateDashboardTables_Staging
https://github.com/cagov/covid-static-data/tree/CovidStateDashboardTables_Staging

CovidStateDashboardTables_Staging branch

---

CovidTranslationPrApproval/AutoApprover.js

Theory, taking longer than 10 seconds to re-validate PRs after one is approved.  Increasing time, might help.

Auto-Approver doubling approval delay between merges

---

package-lock.json
package.json

The new version of this Azure function runs on Linux instead of Windows and seems like that doesn't install packages in subfolders when there is a root level package.json
Moved the autobuilder packages to root

add package to root level for auto builder

---

CovidEquityData/index.js
common/SQL/CDT_COVID/Equity/schema/HealthEquityData/input/fail/invalid county.json
common/SQL/CDT_COVID/Equity/schema/HealthEquityData/input/sample.json
common/SQL/CDT_COVID/Equity/schema/HealthEquityData/input/schema.json
common/SQL/CDT_COVID/Equity/schema/HealthEquityData/output/fail/invalid county.json
common/SQL/CDT_COVID/Equity/schema/HealthEquityData/output/sample.json
common/SQL/CDT_COVID/Equity/schema/HealthEquityData/output/schema.json

Adding input output validators for "healthequity-" datasets.

Health equity validation

---

CovidEquityData/worker.js
common/SQL/CDT_COVID/Equity/schema/StatewideData/input/fail/invalid date.json
common/SQL/CDT_COVID/Equity/schema/StatewideData/input/sample.json
common/SQL/CDT_COVID/Equity/schema/StatewideData/input/schema.json

Validating the "statewide" dataset
(All done with equity dataset validation)

Equity statewide dataset validation

---

CovidStateDashboardV2/function.json
CovidStateDashboardV2/index.js
CovidStateDashboardV2/readme.md
CovidStateDashboardV2/worker.js

(still a combo PR)
Build at 7:45.  Merge at 9am.
Sample output...
https://github.com/cagov/covid-static-data/pull/73
Remove these when deployed...
https://github.com/cagov/covid-static/tree/master/data/infections-by-group
https://github.com/cagov/covid-static/blob/master/data/daily-stats-v2.json

moved Daily Stats and Infections by group to new repo

---

CovidTranslationPrApproval/AutoApprover.js
CovidTranslationPrApproval/index.js

Adding a AutoApprover report when it does something.
Also removing the status checks, since we don't need them and they might slow merge deployment

AutoApprover messaging improvements

---

CovidTranslationPrApproval/worker/index.js

allowing special 8207 code for RTL display

allowing arabic rtl chars

---

CovidTranslationPrApproval/AutoApprover.js

attempting to reduce skips by extending PR approval delay

extending PR wait time to 30s from 20s.

---

package.json

Adding a link to this repo in the package file.
About...
https://stackoverflow.com/questions/48378842/how-to-add-link-of-my-github-repo-to-npm-package

Putting repo link in package

---

CovidTranslationPrApproval/AutoApprover.js

- Making sure close together labels are processed
- Attempting cache busting for PR refreshes.

AutoApprover improvements

---

CovidStateDashboardTables/function.json
CovidStateDashboardTables/index.js

Change from every day to M-F for... 
"Covid Dashboard Tables - Tests",
"Covid Dashboard Tables - Patients",
"Covid Dashboard Tables - Cases/Deaths"

State Dash Monday - Friday

---

CovidStateDashboardTables/function.json
CovidStateDashboardTables/index.js

Revert "State Dash Monday - Friday"

---

CovidStateDashboardTables/function.json
CovidStateDashboardTables/index.js

Re-merging the reverted fix from last week to pause chart updates on weekends.

Revert "Revert "State Dash Monday - Friday""

---

CovidPostvaxData/daily-postvax-data.js
CovidPostvaxData/worker.js

Rewrite to match changes made to StateDashboardVaccines process.

Added support for writing to CovidStateDashboardPostvax_Staging. 

---

CovidPostvaxData/worker.js

Sample of how other similar Crons need to be modified.
Preproduction branch now exists (I made one).

Modified Wednesday Postvax Cron job to make its PR to preproduction branch instead of main.

---

CovidPostvaxData/worker.js
CovidStateDashboardTables/worker.js
CovidStateDashboardV2/worker.js
CovidStateDashboardVaccines/worker.js
CovidVaccineHPIV2/worker.js

* Moved several crons to merge to preproduction instead of main. 
* Scheduled several crons earlier 
* Goal is to be ready to do preproduction->main at 9:20 (and publish charts at 9:30 or 9:25 if possible).

Moved several crons to merge to preproduction instead of main. 

---

CovidTestPacificTime/function.json
CovidTestPacificTime/index.js

Testing use of WEBSITE_TIME_ZONE variable to set Pacific time zone for trigger.

Testing pacific time.

---

.eslintrc.json
CovidTranslationPrApproval/AutoApprover.js
package-lock.json
package.json

Covid Autoapprover Rollup Data Enrichment Robot (CARDER) 
By using the tags 'Add to Rollup' Prs will have their tags copied into a rollup PR.

Rollup support

---

.eslintrc.json
CovidTranslationPrApproval/AutoApprover.js
package-lock.json
package.json

Reverts cagov/Cron#224
Missing the merge part.  Rolling back.

Revert "Rollup support"

---

CovidEquityData/function.json
CovidPostvaxData/function.json
CovidStateDashboardTables/function.json
CovidStateDashboardV2/function.json
CovidStateDashboardVaccines/function.json
CovidVaccineEquity/function.json
CovidVaccineHPIV2/function.json

_Not to be merged_ until Sunday evening 11/7 (Jim'll take care of it)
All CRON-like timer tasks that have a specific hour launch will be moved forward 1 hour in GMT, to account for a change from -07:00 to -08:00 for Pacific time.

Adjustments for coming out of Daylight Savings

---

.vscode/launch.json
common/SQL/CDT_COVID/variants-data/schema/schema.json
common/SQL/CDT_COVID/variants-data/schema/tests/pass/sample_variants.json

updating schema to support required fields and minimum/maximum lengths.
Adding schema dev support.

Variants schema updates + dev

---

CovidPostvaxData/index.js
CovidPostvaxData/worker.js

Tested locally (although there were no changes, so nothing was pushed).

Modified postvax Cron to use new github tree push.

---

.vscode/launch.json
CovidStateDashboardTablesTests/debug.js
CovidStateDashboardTablesTests/index.js
CovidStateDashboardTablesTests/worker.js
package-lock.json
package.json

Adding better slack logging to Covid State Dashboard Tables - Tests.

ready to start reporting more slack info

---

CovidAutoBuilder/worker.js

This Cron used to only build if it detected a data update. These data updates are no longer reliable on weekends, so I'm just forcing a build at 9:25 and 9:30, which is the normal build time.

Greatly simplified auto-builder.

---

package-lock.json
package.json

Revert "Bump node-fetch from 2.6.6 to 3.1.1"

---

common/schemaTester/index.js

removing a direct fetch lib reference that was blocking upgrading versions.

Fixing direct fetch lib reference

---

CovidEquityData/function.json
CovidPostvaxData/function.json
CovidStateDashboardSummary/function.json
CovidStateDashboardTablesCasesDeaths/function.json
CovidStateDashboardTablesHospitals/function.json
CovidStateDashboardTablesTests/function.json
CovidStateDashboardVaccines/function.json
CovidVaccineEquity/function.json
CovidVaccineHPIV2/function.json
CovidVariantsData/function.json
CovidVariantsDataPreview/function.json

-- DO NOT MERGE YET -- (to be merged Saturday afternoon)

Added daylight savings adjustments for Sunday.

---

CovidPostvaxData/index.js
CovidPostvaxData/worker.js
CovidStateDashboardSummary/index.js
CovidStateDashboardTablesCasesDeaths/index.js
CovidStateDashboardTablesHospitals/index.js
CovidStateDashboardTablesTests/index.js
CovidStateDashboardVaccines/index.js
CovidVaccineEquity/index.js
CovidVaccineHPIV2/index.js
CovidVariantsData/index.js
CovidVariantsDataPreview/index.js
sandbox/index.js

Updated several Slack messages to indicate accurate scheduling info (e.g. Tue,Fri instead of daily)
Added a service to provide preview data (on late Tuesday) for the Postvax chart (which now updates Friday).

Added Postvax Preview service. Updated messages with correct schedule info.

---

CovidTestTrigger/debug.js
CovidTestTrigger/function.json
CovidTestTrigger/index.js

Currently experiencing some differences between Azure and local runs for my implementation of OAuth login.  Testing on Azure via the Cron Timer is cumbersome, so I'm adding this trigger function to make it easier to trigger tests on Azure.

Addded test trigger for testing Azure functionality.

---

CovidEquityData/worker.js
CovidPostvaxData/daily-postvax-data.js
CovidStateDashboardSummary/daily-stats-v2.js
CovidStateDashboardSummary/infections-by-group.js
CovidStateDashboardTablesCasesDeaths/worker.js
CovidStateDashboardTablesHospitals/worker.js
CovidStateDashboardTablesTests/worker.js
CovidVariantsData/weekly-variants-data.js

Several CRONs that previously used CDT snowflake are now using the CDPH snowflake with the new service account that uses OpenAuth. 
@carterm  - we can only run this code locally on our AWS server instance, due to CDPH security restrictions (when the OAuth service account is used, we can't run the code on unapproved IP addresses).  When you have a moment, I'll work with you on getting access.

Repointed several CRONs from CDT to CDPH snowflake.

---

CovidEquityData/function.json
CovidEquityData/index.js

Post email discussion, we are moving Equity pulls from Tuesday to Wednesday to guarantee data completeness (for Friday).

Moved weekly Equity pull from Tuesday to Wednesday.

---

common/SQL/CDTCDPH_VACCINE/statedashboard-vaccines/eligiblepopulation.sql

-- DO NOT MERGE --
Waiting for approval on this one.  Likely goes into effect on 7/8

Removed >= 5 age clause for denominator. 

---

CovidPostvaxDataNoboost/daily-postvax-data.js
common/SQL/CDT_COVID/postvax-data-v2/MonthlyRates.sql

Added additional data from COVID.DEVELOPMENT.CDPH_POSTVAX_CASE_HOSP_DEATH_ANYVAX_MONTH_RATES table showing most recent monthly rate changes.

Added monthly summary data.

---

PantheonService/debug.js
PantheonService/function.json
PantheonService/index.html
PantheonService/index.js
common/avantPage.js
common/fetchJSON.js

Copied and minimally tweaked from older repo wordpress-integration-api.

Added Pantheon Service trigger.

---

CovidEquityData/function.json

We're chasing a bit of a moving target at this point

move back equity data timing

---

CovidPostvaxDataPreviewNoboost/index.js
common/timeOffCheck/index.js

I'll do a trial run shortly to make sure I didn't break anything.

Added optional day_delta parameter to snooze checker.

---

CovidEquityImpact/index.js
CovidEquityImpactPreview/index.js
common/timeOffCheck/index.js

This PR supplements #323 by changing the other health equity jobs to run once a month at the right time.

He monthly
