cagov/Cron

- CovidStateDashboard/datasetUpdates/index.js
Now that the tiers are set in Wordpress, we can safely update the daily stats again.
> Remove tier dates - auto-approve stats

- CovidWeeklyTierUpdateHttpTrigger/index.js
Cron job is not completing because the slack reporting is using the old object.
> fixing slackbot notification (preventing error)

- covidE2E/package.json
- package.json
The package names were not passing the regex validation.
`String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$".`
> Package name fix

- CovidStateDashboardV2/worker.js
New Vaccines view, with legacy field names.
If we can get data as single column json like this in the future, it will reduce our data filtering burden.
> Using new vaccines view

- CovidTranslationPrApproval/worker/index.js
Aaron and I worked out some issues with translation approval.
- Changed approval direction to newest first
- No longer stopping when finding a problem (unless there is an Error)
- Removed a check for "diverged" status
(Need to do more research on compare conflicts)
> changing approval direction and conditions

- CovidStateDashboard/function.json
- CovidStateDashboardV2/function.json
A temporary stoppage so we can deploy state-dash later in the day.  These will be turned back on in a day or two.  In the meantime, Crons should be run locally when data refreshes are needed.
> Turned off automatic running of state dash crons until March. 

- CovidVaccineEquity/worker.js
- common/SQL/CDTCDPH_VACCINE/vaccines_by_age.sql
- common/SQL/CDTCDPH_VACCINE/vaccines_by_gender.sql
- common/SQL/CDTCDPH_VACCINE/vaccines_by_race_eth.sql
- package-lock.json
- package.json
Fixes an issue with unidentified categories preventing deployment.
Moves all 'Unable to report due to policy/law' to 'unknown' in the data.
No longer adds "Unknown" to age data.
Uses a new view "CA_VACCINE.VW_TAB_INT_ALL"
created...
https://github.com/cagov/covid-static/pull/211
> Vaccine Equity Data Race/Ethnicity category fix

- CovidStateDashboardV2/worker.js
Branch name of created PR was not being retained, causing 404 errors because the seconds on the new branch name would change.
Fixes...
Error: 404 error making request get https://api.github.com/repos/cagov/covid-static/contents/data/daily-stats-v2.json: "Not Found"
> Bug fix v2 dash branch naming

- CovidTranslationPrApproval/worker/index.js
This should prevent the deployment of non-printable translations.
> Preventing non printable chars in translations

- README.md
Added this - let's use this PR to establish consistency in our date / date time formats.
Current info: 
* Our preferred format for dates is `YYYY-MM-DD`. Example `published_date: "2021-03-17`. 
* We do not have a lot of instances of publishing datetime formatted strings, but our preferred format for datetime is `YYYY-MM-DDTHH:MM:SSZ` which expresses times in GMT, and a use DATETIME in the field name. Example `published_datetime: "2021-03-17T12:47:12Z`.
* Our servers run on GMT.
* Our dates are set to `@TBD` timezone in `standard` time.
* We (will) use lowercase attributes for `meta` data that is programatically updated, such as `published_date` - this matches most API implementations.
> update note about datetime

- common/SQL/CDTCDPH_VACCINE/vaccine_hpi_v2/vaccine_doses.sql
Per Rui Zhao:
https://github.com/cagov/Cron/blob/master/common/SQL/CDTCDPH_VACCINE/vaccine_hpi_v2/vaccine_doses.sql This is the only query that uses the table rather than the view.
common/SQL/CDTCDPH_VACCINE/vaccine_hpi_v2/vaccine_doses.sql
select
HPIQUARTILE
,count(vax_event_id)
from CA_VACCINE.CA_VACCINE.TBL_DERIVED_BASE_DOSES_ADMIN
group by 1
Show more
<https://github.com/cagov/Cron|cagov/Cron>cagov/Cron | Added by GitHub
There is a possibility that the view and table can show different numbers since the table is usually created once per day, and some times the source data is updated later on. This actually happened today, and the table was updated later on, but your HPI chart 2 has the old table's dated numbers.
In effect, your chart 2 right now doesn't agree with your SQL's output. …
> change sql per CDPH

- CovidVaccineEquity/index.js
Trying this for vaccine equity first.
Slack debug messages should be one post per run with PR created and end time as replies.
Exception details should still post separately.
> Bundling testingbot messages into single post

- CovidEquityData/index.js
- CovidStateDashboardV2/worker.js
- CovidVaccineEquity/worker.js
- CovidVaccineHPIV2/worker.js
- CovidWeeklyTierUpdate/doUpdate.js
Adding a 5 second delay before attempting to auto-approve PRs.  Should take care of 405 errors.
> Adding sleep code before all PR approvals

- CovidTranslationPrApproval/AutoApprover.js
The process will add the "PublishASAP" label to any PR that is ready to go.  That will ensure that they are deployed in the next run if there is a connection issue.
The process will only deploy "PublishASAP" labels, assuming the stop button label is off.
> Adding Publish labels to avoid missing approvals

- CovidVaccineEquity/function.json
- CovidVaccineEquity/index.js
- CovidVaccineEquity/readme.md
- CovidVaccineEquity/worker.js
Moving run to covid-static-data.  Building at Wed 8am, publishing at 9:15am.
For...
https://digital-ca-gov.atlassian.net/browse/CCG-2228
Test run here...
https://github.com/cagov/covid-static-data/pull/70
Remove this folder after merge...
https://github.com/cagov/covid-static/tree/master/data/vaccine-equity
> Vaccine Equity moved to static-data

- CovidEquityData/readme.md
- CovidEquityData/worker.js
No workflow changes, since it writes to a staging folder anyway.
Have to wait till existing PR is approved before approving this one
https://github.com/cagov/covid-static/pull/673
(PR Approved...need to wait for data migration)
https://github.com/cagov/covid-static-data/pull/84
Remove these folders after deploying...
https://github.com/cagov/covid-static/tree/master/data/to-review
https://github.com/cagov/covid-static/tree/master/data/reviewed
> moving CovidEquityData to new repo

- CovidStateDashboardTables/worker.js
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/confirmed-cases.json
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/confirmed-deaths.json
Comment: Currently when the data is processed, the DATE fields (which are simple YYYY-MM-DD) are converted into first-class date objects, and then converted back to the same string format for the json. This creates some ugliness -- in order to compare two dates I have resorted to a string-conversion since (a == b) doesn't work for dates. It would be better, in my opinion, to treat the dates as strings...  But I'm not gonna bother with it today.
> Added daily averages to cases/deaths tables.

- CovidTranslationPrApproval/AutoApprover.js
Any PRs that have deploy tags will be deployed, regardless of branch.
> Removing branch filter for autoapprover

- CovidPostvaxData/worker.js
- CovidTranslationPrApproval/AutoApproverLabels.json
- CovidVaccineEquity/worker.js
- CovidVaccineHPIV2/worker.js
* Added all missing timing tags from 8:30 to 9:20 at 5 minute increments. We were missing 8:45, which was already in use and not triggering.
* Moved Wednesday merges to the 8:30-8:35 time frame, so they won't slow down the existing daily cadence (note that PR merges can only happen one per 5 minutes in the current system).
* Fixed VaccinesEquity to also merge to preproduction rather than main.
> Pipeline fixes for Wednesdays

- CovidPostvaxData/function.json
- CovidPostvaxData/index.js
- CovidStateDashboardTables/function.json
- CovidStateDashboardTables/index.js
- CovidStateDashboardVaccines/function.json
- CovidStateDashboardVaccines/index.js
Changed timing on three jobs to meet 2 goals:
1) No concurrent jobs.
2) No jobs running exactly on the hour (when many people schedule their jobs).  We've had time-out issues with our longer 7am job.
> Timing tweaks for 3 jobs.

- common/SQL/CDTCDPH_VACCINE/vaccine_hpi_v2/schema/input/schema.json
- common/SQL/CDTCDPH_VACCINE/vaccine_hpi_v2/schema/output/schema.json
The Vaccine HPI query failed today because a field we don't use VACCINE_RATIO exceeded 1.  Will have CDPH investigate what is going on, but turned off the "<= 1" requirement for now.  Ran the job locally with these settings to generate today's data.
> Loosened rules on Vaccine HPI for a field we don't use.

- CovidStateDashboardTables/worker.js
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/confirmed-cases.json
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/confirmed-deaths.json
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/icu-beds.json
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/patients.json
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/positivity-rate.json
- common/SQL/CDT_COVID/CovidStateDashboardTables/schema/output/total-tests.json
This is to prevent false PUBLISH_DATES on files which have unchanged data. 
We are now tracking publishing date for these files by tracking commits to github. Changing the publishing date for an otherwise unchanged file causes a false commit, and prevents us from tracking true changes, which we need to
track in order to display accurate dates on the State Dashboard.
At the moment, no-one is consu
> Removed meta.PUBLISHED_DATE on StateDashboardTables files. 

- CovidStateDashboardTablesTests/worker.js
- common/schemaTester/index.js
This is actually a smaller way to send the validation content.  Wait till we are ok with previous version before using this one.
> sending JSON raw instead of encoded

- CovidStateDashboardVaccines/daily-vaccines-sparkline.js
This duplicates some vaccination-related data currently stored in data/daily-stats-v2.json into the file
data/dashboard/vaccines/sparkline.json.
The reason for this is the daily-stats-v2 file needs to run every day, due to the the presence of hospitalization and ICU data, which updates every day.  
However, at CDPH's request, we need to pause vaccination data publication on weekends.  
CDPH is still writing this data into snowflake, but we need to skip reading it on the days they don't wish to publish. 
So I'm moving the vaccination related summary data into a file that is vaccine related, and already being paused on weekends.
After CDPH stops referencing the vax data from daily-stats-v2.json on their page, I will stop including the data there.  For now, the data appears in both …
> Copying vaccine summary data into dashboard/vaccinations/sparklines.

- CovidStateDashboardTablesCasesDeaths/function.json
- CovidStateDashboardTablesCasesDeaths/index.js
- CovidStateDashboardTablesTests/function.json
- CovidStateDashboardTablesTests/index.js
- CovidStateDashboardVaccines/function.json
- CovidStateDashboardVaccines/index.js
- common/timeOffCheck/index.js
Currently, several Crons need pausing on both week-days, and holidays. Currently we are only pausing on weekdays, via the Cron-timing specification in functions.json, and holidays require manual intervention.  The intent of this patch is to reduce day-of-execution interventions.  It also provides explanatory messages to the testing channel when jobs are skipped for the day.
This modification adds a lookup function **_isIdleDay_**, used to determine if a job should run or not. The function returns _true_ if it's a weekend or holiday.  Such a job is considered "snoozed" for the day and gets a :zzz: emoji instead of a checkmark.  The three jobs that will use this feature are set to run every day in this patch, instead of Mon-Fri, as before, so that there are more informative messages on …
> Added snoozing feature for three daily jobs that don't run on weekends nor holidays.

- CovidVariantsData/worker.js
- CovidVariantsDataPreview/function.json
- CovidVariantsDataPreview/index.js
- CovidVariantsDataPreview/readme.md
- sandbox/index.js
The CovidVariantsData job, which pulls data for the Variants chart, runs on Thursday morning.
We generally preview this chart on Wednesday afternoons, and I have been doing manual runs to produce these previews, while re-tagging/removing the resultant PRs.
This patch adds a second Trigger function CovidVariantsDataPreview, which piggy-backs off the code in CovidVariantsData, but updates the CovidStateDashboardVariants_Staging branch only without submitting a PR to master.
The workhorse function now receives a parameter, previewOnly which is used to inhibit the PR to master part of the task.
This new trigger is currently scheduled to run at 1pm, 2pm and 3pm on Wednesday.  This triggering will be refined when we get a more reliable update schedule.
> Added preview-only version of CovidVariantsData.

- CovidAutoBuilder/function.json
- CovidPostvaxData/function.json
- CovidStateDashboardSummary/function.json
- CovidStateDashboardTablesCasesDeaths/function.json
- CovidStateDashboardTablesHospitals/function.json
- CovidStateDashboardTablesTests/function.json
- CovidStateDashboardVaccines/function.json
- CovidVaccineEquity/function.json
- CovidVaccineHPIV2/function.json
- CovidVariantsData/function.json
We are moving to a new schedule in which most daily rollouts happen only on Tuesday and Friday mornings, and most weekly rollouts happen on Friday.  This adjusts most of the pipeline for this new schedule.  Equity is still processing Tuesday, as it is still up in the air.  Some of the weekly jobs moved to Friday may get moved to Tuesday, but most of this is confirmed.
> Changed daily crons to Tue/Fri.  Changed most weekly crons to Fri only.

- CovidStateDashboardTablesCasesDeaths/worker.js
Based on a communication from Lauren Nelson, this modifies the logic for computing cases and deaths daily average to re-interpret the meaning of "pending date" such that the averaged period is moved closer to the present by one day.
> Shifted average window for cases and deaths by one day.

- common/timeOffCheck/index.js
This will skip the morning merge on Tuesday July 5, since we expect a data update to be later in the day and handled manually.
> Updated cron holidays to include 2022-07-05

- CovidAutoBuilder/function.json
This PR is meant to address a situation where the 9:25 auto build wins a race against, for example, the equity PR merge (which results in another build being required).
> add additional trigger to CovidAutoBuilder

- common/SQL/CDT_COVID/CovidStateDashboardTablesCasesDeathsTests/schema/output/confirmed-cases.json
- common/SQL/CDT_COVID/CovidStateDashboardTablesCasesDeathsTests/schema/output/confirmed-deaths.json
Today marks 901 days since 2020-03-01, which is the date our data starts at. I'm imagining there is no technical issue with the charts displaying 900+ cases, so this fix buys us 100 more days.
I'll set a slack reminder to check on this issue in ~90 days from now...
> added 100 days to max case/death data length

- CovidStateDashboardTablesTests/worker.js
- common/SQL/CDT_COVID/CovidStateDashboardTablesCasesDeathsTests/schema/output/confirmed-cases.json
- common/SQL/CDT_COVID/CovidStateDashboardTablesCasesDeathsTests/schema/output/confirmed-deaths.json
- common/SQL/CDT_COVID/CovidStateDashboardTablesCasesDeathsTests/schema/output/positivity-rate.json
- common/SQL/CDT_COVID/CovidStateDashboardTablesCasesDeathsTests/schema/output/total-tests.json
- common/SQL/CDT_COVID/CovidStateDashboardTablesTests/schema/output/positivity-rate.json
- common/SQL/CDT_COVID/CovidStateDashboardTablesTests/schema/output/total-tests.json
- Extended a number of allowed data lengths to 1200, per slack suggestion
- Remote validation was failing for tests data so I made the request sizes smaller
This code was used to rerun 2 failed jobs from this morning.
> Extend tests len

- CovidAutoBuilder/function.json
- CovidEquityData/function.json
- CovidEquityData/index.js
- CovidEquityImpact/function.json
- CovidEquityImpact/index.js
- CovidEquityImpactPreview/function.json
- CovidEquityImpactPreview/index.js
- CovidPostvaxDataNoboost/function.json
- CovidPostvaxDataNoboost/index.js
- CovidPostvaxDataPreviewNoboost/function.json
- CovidPostvaxDataPreviewNoboost/index.js
- CovidStateDashboardSummary/function.json
- CovidStateDashboardSummary/index.js
- CovidStateDashboardTablesCasesDeaths/function.json
- CovidStateDashboardTablesCasesDeaths/index.js
- CovidStateDashboardTablesHospitals/function.json
- CovidStateDashboardTablesHospitals/index.js
- CovidStateDashboardTablesTests/function.json
- CovidStateDashboardTablesTests/index.js
- CovidStateDashboardVaccines/function.json
- CovidStateDashboardVaccines/index.js
- CovidVariantsData/function.json
- CovidVariantsData/index.js
- CovidVariantsDataPreview/function.json
- CovidVariantsDataPreview/index.js
Excuse the typo in the branch name...
Changes:
- Moved Tuesday/Friday jobs to Thursday only
- Updated slack messages with new timings
- Moved equity data pipeline sooner in the day so that the approver has a full day to look at it. I verified that all the tables used by this pipeline are updated on Tuesday morning/afternoon, so a Wednesday update should be perfectly fine. The equity impact preview pipeline was similarly modified to run on Wed morning.
- Got rid of 2 Variants Preview pipeline runs since the data hasn't been arriving as early as those pipelines were running
> moved jobs to run on thursday

- CovidEquityData/index.js
- CovidEquityImpactPreview/function.json
- CovidEquityImpactPreview/index.js
- CovidVariantsDataPreview/function.json
- CovidVariantsDataPreview/index.js
- Moved the equity pipelines that write to the "to-review" location to Wednesday after 11 am based on slack feedback from Lauren Nelson
- Moved the variant preview pipeline to Tuesday afternoon based on feedback from Mayuri Panditrao
I am fairly confident there will be more changes to pipeline timing within the next week but this is what we know currently.
> more pipeline scheduling tweaks

- CovidEquityData/function.json
- CovidEquityData/index.js
- CovidEquityImpactPreview/function.json
- CovidEquityImpactPreview/index.js
@jbum FYI a new health equity schedule was approved so that there is a larger window of time for the data to be approved:
1. Data team generates new tables at some point on **Thursday**
2. We generate PR and staged data on the following **Monday**
3. Health equity team has until **Wednesday** evening to approve the staged data
4. Staged data is merged on Thursday 
To accommodate this shift in schedule, no updates to health equity data will happen this week. Additionally, the data will be 1 week older than it would have been otherwise.
> moved equity data pipelines to monday

- CovidEquityData/index.js
- common/timeOffCheck/index.js
Health equity data updates are now on a monthly schedule. The data team will move the data into snowflake on the first Friday of every month therefore the Monday we need to not snooze on will be the first Monday in the month that comes after a Friday.
> Health equity to monthly

- CovidAutoBuilder/function.json
- CovidEquityData/function.json
- CovidEquityImpact/function.json
- CovidEquityImpactPreview/function.json
- CovidPostvaxDataNoboost/function.json
- CovidPostvaxDataPreviewNoboost/function.json
- CovidPostvaxDataPreviewNoboost/index.js
- CovidStateDashboardSummary/function.json
- CovidStateDashboardTablesCasesDeaths/function.json
- CovidStateDashboardTablesHospitals/function.json
- CovidStateDashboardTablesTests/function.json
- CovidStateDashboardVaccines/function.json
- CovidVariantsData/function.json
- CovidVariantsDataPreview/function.json
- CovidVariantsDataPreview/index.js
This is mainly for daylight savings changes but there are 2 bonus updates:
- moved CovidPostvaxDataPreviewNoboost earlier in the day since Lauren said their automation runs earlier now
- moved CovidVariantsDataPreview to Wednesday since the variants team told me that their updates will be later now. The timing of this job is still subject to change...
> changes for end of DST
